version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  web:
    build: .
    command: -c "entrypoint.sh && daphne my_site.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
