name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      env:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      run: |
        echo "POSTGRES_DB=${POSTGRES_DB}" >> $GITHUB_ENV
        echo "POSTGRES_USER=${POSTGRES_USER}" >> $GITHUB_ENV
        echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> $GITHUB_ENV
        echo "POSTGRES_HOST=${POSTGRES_HOST}" >> $GITHUB_ENV
        echo "POSTGRES_PORT=${POSTGRES_PORT}" >> $GITHUB_ENV
        echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> $GITHUB_ENV
        echo "DJANGO_DEBUG=${DJANGO_DEBUG}" >> $GITHUB_ENV
        echo "DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}" >> $GITHUB_ENV

    - name: Create env file
      run: |
        echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
        echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
        echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
        echo "POSTGRES_HOST=${POSTGRES_HOST}" >> .env
        echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env
        echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> .env
        echo "DJANGO_DEBUG=${DJANGO_DEBUG}" >> .env
        echo "DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}" >> .env

    - name: Build the container
      run: |
        docker-compose up --build -d
